[pytest]
testpaths = src/tests
python_files = test_*.py
addopts = -v -s -qq
asyncio_mode = auto

markers =
  auth: auth functionality tests
  stocks: stocks tests
  users: users
  api: api
  model: model
