"""add exchange to Stocks

Revision ID: 28ac9c23c96e
Revises: 531fbb87bef6
Create Date: 2026-03-05 11:16:10.319850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28ac9c23c96e'
down_revision: Union[str, Sequence[str], None] = '531fbb87bef6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocks', sa.Column('exchange', sa.String(), nullable=True))
    op.create_index(op.f('ix_stocks_exchange'), 'stocks', ['exchange'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stocks_exchange'), table_name='stocks')
    op.drop_column('stocks', 'exchange')
    # ### end Alembic commands ###
